//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Address
{
	public virtual object #city_id
	{
		get;
		set;
	}

	public virtual object #district_id
	{
		get;
		set;
	}

	public virtual object address_id
	{
		get;
		set;
	}

	public virtual object description
	{
		get;
		set;
	}

	public virtual object longitude
	{
		get;
		set;
	}

	public virtual object latitude
	{
		get;
		set;
	}

	public virtual object postal_code
	{
		get;
		set;
	}

	public virtual District District
	{
		get;
		set;
	}

	public virtual User User
	{
		get;
		set;
	}

	public virtual Company Company
	{
		get;
		set;
	}

}

