//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Advertissment
{
	public virtual object advertissement_id
	{
		get;
		set;
	}

	public virtual object #adverted_user_id
	{
		get;
		set;
	}

	public virtual object #admin_id
	{
		get;
		set;
	}

	public virtual object created_at
	{
		get;
		set;
	}

	public virtual object advertissement_type_id
	{
		get;
		set;
	}

}

