//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Bill
{
	public virtual object created_at
	{
		get;
		set;
	}

	public virtual object bill_id
	{
		get;
		set;
	}

	public virtual object #order_id
	{
		get;
		set;
	}

}

