//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Cart_detail
{
	public virtual object cart_detail_id
	{
		get;
		set;
	}

	public virtual object #cart_id
	{
		get;
		set;
	}

	public virtual object #store_product_id
	{
		get;
		set;
	}

	public virtual object quantity
	{
		get;
		set;
	}

}

