//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Cart
{
	public virtual object name
	{
		get;
		set;
	}

	public virtual object cart_id
	{
		get;
		set;
	}

	public virtual object #currency_id
	{
		get;
		set;
	}

	public virtual object #belongs_to
	{
		get;
		set;
	}

	public virtual User User
	{
		get;
		set;
	}

	public virtual IEnumerable<Cart_detail> Cart_detail
	{
		get;
		set;
	}

}

