//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Color
{
	public virtual object color_id
	{
		get;
		set;
	}

	public virtual object name
	{
		get;
		set;
	}

	public virtual object value
	{
		get;
		set;
	}

}

