//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// RECEIVERTYPE
/// -- PRODUCT
/// -- POST
/// -- SELLER
/// </remarks>
public class Comment
{
	public virtual object inserted_at
	{
		get;
		set;
	}

	public virtual object content
	{
		get;
		set;
	}

	public virtual object #receiver_id
	{
		get;
		set;
	}

	public virtual object comment_id
	{
		get;
		set;
	}

	public virtual object #inserted_by
	{
		get;
		set;
	}

	public virtual object receiver_type
	{
		get;
		set;
	}

}

