//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// -- NEW
/// -- USED
/// -- OPEN_BOX
/// -- NOT_WORKING_PARTIALLY
/// 
/// </remarks>
public class Condition
{
	public virtual object title
	{
		get;
		set;
	}

	public virtual object condition_id
	{
		get;
		set;
	}

}

