//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Country
{
	public virtual object country_id
	{
		get;
		set;
	}

	public virtual object name
	{
		get;
		set;
	}

	public virtual object phone_code
	{
		get;
		set;
	}

}

