//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// INITIALS
/// -- DH
/// 
/// TITLE
/// -- DIRHAM
/// </remarks>
public class Currency
{
	public virtual object title
	{
		get;
		set;
	}

	public virtual object currency_id
	{
		get;
		set;
	}

	public virtual object currency_initials
	{
		get;
		set;
	}

	public virtual object description
	{
		get;
		set;
	}

	public virtual IEnumerable<Cart> Cart
	{
		get;
		set;
	}

}

