//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Delivery
{
	public virtual object delivery_date
	{
		get;
		set;
	}

	public virtual object delivery_id
	{
		get;
		set;
	}

	public virtual object #delivery_method_id
	{
		get;
		set;
	}

	public virtual object description
	{
		get;
		set;
	}

	public virtual object #delivery_adress_id
	{
		get;
		set;
	}

	public virtual object inserted_at
	{
		get;
		set;
	}

	public virtual Delivery_method Delivery_method
	{
		get;
		set;
	}

}

