//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// -- Actived
/// -- Deactivated
/// </remarks>
public class Discount
{
	public virtual object discount_id
	{
		get;
		set;
	}

	public virtual object created_at
	{
		get;
		set;
	}

	public virtual object #created_by
	{
		get;
		set;
	}

	public virtual object start_date
	{
		get;
		set;
	}

	public virtual object end_date
	{
		get;
		set;
	}

	public virtual object discount_status
	{
		get;
		set;
	}

}

