//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class District
{
	public virtual object district_id
	{
		get;
		set;
	}

	public virtual object name
	{
		get;
		set;
	}

	public virtual object #city_id
	{
		get;
		set;
	}

	public virtual City City
	{
		get;
		set;
	}

}

