//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// FOLLOW TYPE
/// -- Seller
/// -- Store
/// </remarks>
public class Follow
{
	public virtual object follow_at
	{
		get;
		set;
	}

	public virtual object follow_id
	{
		get;
		set;
	}

	public virtual object #followed_by
	{
		get;
		set;
	}

	public virtual object #follow_id
	{
		get;
		set;
	}

	public virtual object follow_type
	{
		get;
		set;
	}

	public virtual Store Store
	{
		get;
		set;
	}

}

