//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Model
{
	public virtual object title
	{
		get;
		set;
	}

	public virtual object model_id
	{
		get;
		set;
	}

	public virtual object #brand_id
	{
		get;
		set;
	}

}

