//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Newsletter
{
	public virtual object newsletter_id
	{
		get;
		set;
	}

	public virtual object #mail_id
	{
		get;
		set;
	}

	public virtual object #store_id
	{
		get;
		set;
	}

	public virtual object inserted_at
	{
		get;
		set;
	}

	public virtual object enable
	{
		get;
		set;
	}

}

