//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Open_day_time
{
	public virtual object open_date_time_id
	{
		get;
		set;
	}

	public virtual object day
	{
		get;
		set;
	}

	public virtual object open_time
	{
		get;
		set;
	}

	public virtual object close_time
	{
		get;
		set;
	}

}

