//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// -- DELIVERED
/// -- SHIPPING
/// -- CREATED
/// -- PAYED
/// </remarks>
public class Order_state
{
	public virtual object order_state_id
	{
		get;
		set;
	}

	public virtual object title
	{
		get;
		set;
	}

}

