//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Order_detail
{
	public virtual object order_detail_id
	{
		get;
		set;
	}

	public virtual object #order_id
	{
		get;
		set;
	}

	public virtual object #store_product_id
	{
		get;
		set;
	}

	public virtual object quantity_ordered
	{
		get;
		set;
	}

	public virtual object #sell_tax_id
	{
		get;
		set;
	}

	public virtual object #discount_id
	{
		get;
		set;
	}

	public virtual Store_product Store_product
	{
		get;
		set;
	}

	public virtual Tax Tax
	{
		get;
		set;
	}

}

