//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Payment
{
	public virtual object payment_id
	{
		get;
		set;
	}

	public virtual object #payment_method_id
	{
		get;
		set;
	}

	public virtual object #payment_type_id
	{
		get;
		set;
	}

	public virtual object created_at
	{
		get;
		set;
	}

}

