//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// -- Details
/// -- Totals
/// </remarks>
public class Payment_type
{
	public virtual object payment_type_id
	{
		get;
		set;
	}

	public virtual object name
	{
		get;
		set;
	}

	public virtual object description
	{
		get;
		set;
	}

	public virtual IEnumerable<Payment> Payment
	{
		get;
		set;
	}

}

