//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Post
{
	public virtual object post_id
	{
		get;
		set;
	}

	public virtual object #posted_by
	{
		get;
		set;
	}

	public virtual object content
	{
		get;
		set;
	}

	public virtual object store_id
	{
		get;
		set;
	}

	public virtual object created_at
	{
		get;
		set;
	}

	public virtual Store Store
	{
		get;
		set;
	}

}

