//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Price
{
	public virtual object price
	{
		get;
		set;
	}

	public virtual object price_id
	{
		get;
		set;
	}

	public virtual object #id_product
	{
		get;
		set;
	}

	public virtual object #id_user
	{
		get;
		set;
	}

	public virtual object #price_description_id
	{
		get;
		set;
	}

	public virtual object created_at
	{
		get;
		set;
	}

	public virtual Price_description Price_description
	{
		get;
		set;
	}

	public virtual void get_price()
	{
		throw new System.NotImplementedException();
	}

	private void set_price()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_price()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_price()
	{
		throw new System.NotImplementedException();
	}

	public virtual void add_price()
	{
		throw new System.NotImplementedException();
	}

}

