//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// -- normal
/// -- reduction
/// -- negociation
/// -- store
/// </remarks>
public class Price_description
{
	public virtual object description_id
	{
		get;
		set;
	}

	public virtual object description
	{
		get;
		set;
	}

	public virtual object title
	{
		get;
		set;
	}

}

