//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Product
{
	public virtual object designation
	{
		get;
		set;
	}

	public virtual object weight
	{
		get;
		set;
	}

	public virtual object dimension
	{
		get;
		set;
	}

	public virtual object description
	{
		get;
		set;
	}

	public virtual object product_id
	{
		get;
		set;
	}

	public virtual object #inserted_by
	{
		get;
		set;
	}

	public virtual object inserted_at
	{
		get;
		set;
	}

	public virtual object keywords
	{
		get;
		set;
	}

	public virtual object reference
	{
		get;
		set;
	}

	public virtual object images
	{
		get;
		set;
	}

	public virtual Sub_category Sub_category
	{
		get;
		set;
	}

	public virtual IEnumerable<Color> Color
	{
		get;
		set;
	}

	public virtual Condition Condition
	{
		get;
		set;
	}

}

