//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Provider
{
	public virtual object name
	{
		get;
		set;
	}

	public virtual object provider_id
	{
		get;
		set;
	}

	public virtual object mail
	{
		get;
		set;
	}

	public virtual object phone_id
	{
		get;
		set;
	}

	public virtual object #adress_id
	{
		get;
		set;
	}

	public virtual void add_provider()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_provider()
	{
		throw new System.NotImplementedException();
	}

	public virtual void get_provider()
	{
		throw new System.NotImplementedException();
	}

	public virtual void get_mail()
	{
		throw new System.NotImplementedException();
	}

	public virtual void set_mail()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_mail()
	{
		throw new System.NotImplementedException();
	}

	public virtual void get_name()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_name()
	{
		throw new System.NotImplementedException();
	}

	public virtual void set_name()
	{
		throw new System.NotImplementedException();
	}

	public virtual void get_phone()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_phone()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_phone()
	{
		throw new System.NotImplementedException();
	}

	public virtual void get_provider_id()
	{
		throw new System.NotImplementedException();
	}

}

