//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Return
{
	public virtual object return_id
	{
		get;
		set;
	}

	public virtual object #order_detail_id
	{
		get;
		set;
	}

	public virtual object inserted_at
	{
		get;
		set;
	}

	public virtual object reason
	{
		get;
		set;
	}

	public virtual object return_validated_seller
	{
		get;
		set;
	}

	public virtual object return_validated_customer
	{
		get;
		set;
	}

	public virtual Order_detail Order_detail
	{
		get;
		set;
	}

}

