//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// -- CLIENT -default
/// -- SELLER
/// -- ADMIN
/// </remarks>
public class Role
{
	public virtual object title
	{
		get;
		set;
	}

	public virtual object role_id
	{
		get;
		set;
	}

	public virtual object role_description
	{
		get;
		set;
	}

	public virtual User User
	{
		get;
		set;
	}

}

