//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// RECEIVERTYPE
/// -- Boutique
/// -- Seller
/// -- Product
/// 
/// STAR TYPE
/// -- COMMUNICATION
/// -- PRODUCT QUALITY
/// -- DELAIS DE LIVRAISON
/// -- SERIEUX DU VENDEUR
/// -- DISPONIBILITE
/// </remarks>
public class Star
{
	public virtual object star_id
	{
		get;
		set;
	}

	public virtual object value
	{
		get;
		set;
	}

	public virtual object #customer_id
	{
		get;
		set;
	}

	public virtual object #receiver_id
	{
		get;
		set;
	}

	public virtual object receiver_type
	{
		get;
		set;
	}

	public virtual object star_type
	{
		get;
		set;
	}

	public virtual IEnumerable<Product> Product
	{
		get;
		set;
	}

}

