//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// PRICE TYPE
/// -- FIX
/// -- VARIABLE
/// </remarks>
public class Store_product
{
	public virtual object #added_by
	{
		get;
		set;
	}

	public virtual object store_product_id
	{
		get;
		set;
	}

	public virtual object stock_quantity
	{
		get;
		set;
	}

	public virtual object #unit_price_id
	{
		get;
		set;
	}

	public virtual object #warranty_id
	{
		get;
		set;
	}

	public virtual object visible_on_store
	{
		get;
		set;
	}

	public virtual object images_selected
	{
		get;
		set;
	}

	public virtual object price_type
	{
		get;
		set;
	}

	public virtual object inserted_at
	{
		get;
		set;
	}

	public virtual object modified_at
	{
		get;
		set;
	}

	public virtual object end_date
	{
		get;
		set;
	}

	public virtual object have_return
	{
		get;
		set;
	}

	public virtual object visible_on_store_at
	{
		get;
		set;
	}

	public virtual IEnumerable<Discount> Discount
	{
		get;
		set;
	}

	public virtual Product Product
	{
		get;
		set;
	}

	public virtual IEnumerable<Cart_detail> Cart_detail
	{
		get;
		set;
	}

	public virtual Price Price
	{
		get;
		set;
	}

	public virtual Warranty Warranty
	{
		get;
		set;
	}

	public virtual Seller Seller
	{
		get;
		set;
	}

	public virtual IEnumerable<Provider> Provider
	{
		get;
		set;
	}

}

