//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Users1
{
	public virtual object first_name
	{
		get;
		set;
	}

	public virtual object last_name
	{
		get;
		set;
	}

}

