//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// USER STATE
/// -- Active
/// -- Blocked
/// -- Archived
/// --Banned
/// 
/// GENDER
/// -- MAN
/// -- WOMEN
/// </remarks>
public class User
{
	public virtual object first_name
	{
		get;
		set;
	}

	public virtual object last_name
	{
		get;
		set;
	}

	public virtual object user_id
	{
		get;
		set;
	}

	public virtual object gender
	{
		get;
		set;
	}

	public virtual object #mail_id
	{
		get;
		set;
	}

	public virtual object #language_id
	{
		get;
		set;
	}

	public virtual object #address_id
	{
		get;
		set;
	}

	public virtual object #nationality_country_id
	{
		get;
		set;
	}

	public virtual object #phone_id
	{
		get;
		set;
	}

	public virtual object verified
	{
		get;
		set;
	}

	public virtual object user_state
	{
		get;
		set;
	}

	public virtual object #role_id
	{
		get;
		set;
	}

	public virtual object #default_currency_id
	{
		get;
		set;
	}

	public virtual Currency Currency
	{
		get;
		set;
	}

	public virtual IEnumerable<Price> Price
	{
		get;
		set;
	}

	public virtual Country Country
	{
		get;
		set;
	}

	public virtual Language Language
	{
		get;
		set;
	}

	public virtual IEnumerable<Mail> Mail
	{
		get;
		set;
	}

	public virtual Phone Phone
	{
		get;
		set;
	}

	public virtual IEnumerable<Message> Message
	{
		get;
		set;
	}

	public virtual IEnumerable<Comment> Comment
	{
		get;
		set;
	}

	public virtual IEnumerable<Sub_comment> Sub_comment
	{
		get;
		set;
	}

	public virtual Post Post
	{
		get;
		set;
	}

	public virtual Star Star
	{
		get;
		set;
	}

	public virtual IEnumerable<Follow> Follow
	{
		get;
		set;
	}

	public virtual void long_in()
	{
		throw new System.NotImplementedException();
	}

	public virtual void log_out()
	{
		throw new System.NotImplementedException();
	}

	public virtual void password_recover()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_account()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_pseudo()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_first_name()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_last_name()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_mail()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_password()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_postal_code()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_language_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_phone()
	{
		throw new System.NotImplementedException();
	}

	public virtual void verify_account()
	{
		throw new System.NotImplementedException();
	}

	public virtual void add_user()
	{
		throw new System.NotImplementedException();
	}

	private void get_first_name()
	{
		throw new System.NotImplementedException();
	}

	private void get_last_name()
	{
		throw new System.NotImplementedException();
	}

	private void get_pseudo()
	{
		throw new System.NotImplementedException();
	}

	private void get_phone()
	{
		throw new System.NotImplementedException();
	}

	private void get_gender_id()
	{
		throw new System.NotImplementedException();
	}

	private void get_postal_code()
	{
		throw new System.NotImplementedException();
	}

	private void get_birthday()
	{
		throw new System.NotImplementedException();
	}

	private void set_first_name()
	{
		throw new System.NotImplementedException();
	}

	private void set_last_name()
	{
		throw new System.NotImplementedException();
	}

	private void set_pseudo()
	{
		throw new System.NotImplementedException();
	}

	private void set_mail()
	{
		throw new System.NotImplementedException();
	}

	private void get_mail()
	{
		throw new System.NotImplementedException();
	}

	private void set_passowrd()
	{
		throw new System.NotImplementedException();
	}

	private void set_phone()
	{
		throw new System.NotImplementedException();
	}

	private void set_gender_id()
	{
		throw new System.NotImplementedException();
	}

	private void set_postal_code()
	{
		throw new System.NotImplementedException();
	}

	private void set_language_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_first_name()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_last_name()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_pseudo()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_mail()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_password()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_phone()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_gender_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_postal_code()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_birthday()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_language_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void get_city_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void get_country_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void get_nationality_country_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void set_city_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void set_country_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_city_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_country_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete_nationality_country_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_city_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_country_id()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update_nationality_country_id()
	{
		throw new System.NotImplementedException();
	}

}

