//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class View
{
	public virtual object view_id
	{
		get;
		set;
	}

	public virtual object #user_id
	{
		get;
		set;
	}

	public virtual object #store_product_id
	{
		get;
		set;
	}

	public virtual object inserted_at
	{
		get;
		set;
	}

	public virtual Store_product Store_product
	{
		get;
		set;
	}

	public virtual User User
	{
		get;
		set;
	}

}

