//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>
/// Accorded type
/// -- SELLER
/// -- STORE
/// -- Company
/// -- WEBSITE
/// </remarks>
public class Warranty
{
	public virtual object title
	{
		get;
		set;
	}

	public virtual object description
	{
		get;
		set;
	}

	public virtual object duration
	{
		get;
		set;
	}

	public virtual object warranty_id
	{
		get;
		set;
	}

	public virtual object #accorded_by
	{
		get;
		set;
	}

	public virtual object accorded_type
	{
		get;
		set;
	}

}

